import * as React from 'react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'

function DashboardShell({ role, title, subtitle, children }) {
  const [active, setActive] = React.useState('Overview')
  const navigate = useNavigate()
  const { user, signOut } = useAuth()
  const items = role === 'Faculty' ? ['Overview', 'My courses', 'Learners', 'Assignments', 'Analytics'] : role === 'Admin' ? ['Overview', 'People', 'Courses', 'Reports', 'Settings'] : ['Overview', 'My learning', 'Assignments', 'Calendar', 'Achievements']
  async function handleSignOut() { await signOut(); navigate('/') }
  return <div className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,_#ede9fe_0,_transparent_32%),radial-gradient(circle_at_90%_12%,_#fce7f3_0,_transparent_25%),linear-gradient(135deg,_#faf7ff,_#f1edff_52%,_#fdf4ff)] text-violet-950"><div className="mx-auto flex min-h-screen max-w-[1500px]"><aside className="hidden w-64 shrink-0 border-r border-violet-200/70 bg-white/55 p-5 backdrop-blur-xl lg:block"><button onClick={() => navigate('/')} className="flex items-center gap-3 px-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-violet-600 to-fuchsia-500 text-lg font-black text-white shadow-lg shadow-violet-300">L</span><span><strong className="block text-lg">LumaLearn</strong><small className="text-violet-500">{role} portal</small></span></button><nav className="mt-10 space-y-1">{items.map((item, index) => <button key={item} onClick={() => setActive(item)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium transition ${active === item ? 'bg-violet-600 text-white shadow-lg shadow-violet-200' : 'text-violet-800 hover:bg-violet-100/80'}`}><span className="grid h-6 w-6 place-items-center rounded-lg bg-current/10 text-xs">{index + 1}</span>{item}</button>)}</nav><div className="mt-10 rounded-2xl bg-gradient-to-br from-violet-600 to-fuchsia-500 p-4 text-white shadow-lg shadow-violet-200"><p className="text-xs text-violet-100">Learning streak</p><p className="mt-1 text-2xl font-bold">12 days ✦</p><p className="mt-2 text-xs text-violet-100">Keep the momentum going.</p></div></aside><main className="min-w-0 flex-1 p-4 sm:p-7 lg:p-10"><header className="mb-8 flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-violet-600">{active}</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 text-sm text-violet-700/75">{subtitle}</p></div><div className="flex items-center gap-3"><button className="grid h-11 w-11 place-items-center rounded-2xl border border-violet-200 bg-white/70 text-lg shadow-sm transition hover:-translate-y-0.5 hover:bg-violet-100" aria-label="Notifications">♢</button><button onClick={handleSignOut} className="rounded-xl border border-violet-200 bg-white/70 px-4 py-2 text-sm font-semibold text-violet-800 transition hover:bg-violet-100">Sign out</button><div className="hidden h-11 w-11 place-items-center rounded-2xl bg-violet-200 font-bold text-violet-800 sm:grid">{user?.name?.slice(0, 1)?.toUpperCase() || 'U'}</div></div></header>{children}</main></div></div>
}
export default DashboardShell
