/**
 * Shared mock data used as fallback when database records are empty or during development.
 */

export const MOCK_STUDENT_COURSES = [
  {
    id: 'mock-1',
    title: 'Intro to Machine Learning',
    courseCode: 'CS401',
    instructorName: 'Dr. Alan Turing',
    progress: 85,
    statusBadge: 'Cors badged',
    bannerUrl: null,
  },
  {
    id: 'mock-2',
    title: 'Linear Algebra II',
    courseCode: 'MATH202',
    instructorName: 'Prof. Katherine Johnson',
    progress: 62,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-3',
    title: 'Advanced Web Development',
    courseCode: 'CS350',
    instructorName: 'Dr. Tim Berners-Lee',
    progress: 78,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-4',
    title: 'Linear Learning',
    courseCode: 'CS410',
    instructorName: 'Dr. Alan Turing',
    progress: 85,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-5',
    title: 'Machine Algebra',
    courseCode: 'MATH305',
    instructorName: 'Prof. Katherine',
    progress: 62,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-6',
    title: 'Student Development',
    courseCode: 'CS499',
    instructorName: 'Dr. Tim Berners-Lee',
    progress: 78,
    statusBadge: 'Status',
    bannerUrl: null,
  },
];

export const MOCK_CATALOG_COURSES = [
  {
    id: 'cat-1',
    courseCode: 'CS102',
    title: 'Data Structures & Algorithms',
    description: 'Learn fundamental concepts of data structures and machine learning fundamentals.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 98,
  },
  {
    id: 'cat-2',
    courseCode: 'AI201',
    title: 'Deep Learning Foundations',
    description: 'Explore neural networks and advanced AI concepts to build real-world models.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 95,
  },
  {
    id: 'cat-3',
    courseCode: 'DS301',
    title: 'Business Analytics',
    description: 'Explore neural analysis and charts analytics for business contribution.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Waiting List',
    popularity: 88,
  },
  {
    id: 'cat-4',
    courseCode: 'CS102',
    title: 'Data Structures II',
    description: 'Advanced data structure architectures and computational complexity.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 85,
  },
  {
    id: 'cat-5',
    courseCode: 'AI201',
    title: 'Data Learning & Systems',
    description: 'Explore neural networks and advanced AI concepts on modern hardware.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 91,
  },
  {
    id: 'cat-6',
    courseCode: 'DS301',
    title: 'Advanced Analytics',
    description: 'Data pipelines, predictive algorithms, and statistical decision frameworks.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 82,
  },
  {
    id: 'cat-7',
    courseCode: 'CS102',
    title: 'Data Algorithms & Systems',
    description: 'Distributed memory structures, algorithmic optimizers, and cloud caches.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 89,
  },
  {
    id: 'cat-8',
    courseCode: 'AI201',
    title: 'Data Learning & LLMs',
    description: 'Generative transformer models, prompt engineering, and fine-tuning pipelines.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Waiting List',
    popularity: 96,
  },
  {
    id: 'cat-9',
    courseCode: 'DS301',
    title: 'Quantitative Finance & ML',
    description: 'Algorithmic trading strategies, time-series forecasting, and risk management.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 90,
  },
];

export const MOCK_COURSE_QUIZZES = [
  {
    id: 'quiz-1',
    quizNumber: 'Quiz 1',
    title: 'Control Flow & Loops Quiz',
    questions: 10,
    duration: '20 minuts',
    attemptsAllowed: 3,
    attemptsUsed: 0,
    points: 16,
    status: 'Active',
    colorTheme: 'cyan',
    buttonText: 'Start Attempt',
  },
  {
    id: 'quiz-2',
    quizNumber: 'Quiz 2',
    title: 'Functions & Modules Assessment',
    questions: 10,
    duration: '30 minuts',
    attemptsAllowed: 3,
    attemptsUsed: 1,
    points: 15,
    status: 'Attempted',
    colorTheme: 'amber',
    buttonText: 'Continue Attempt',
  },
  {
    id: 'quiz-3',
    quizNumber: 'Quiz 3',
    title: 'Data Structures Quiz',
    questions: 10,
    duration: '30 minuts',
    attemptsAllowed: 3,
    attemptsUsed: 3,
    points: 16,
    score: 15,
    status: 'Completed',
    colorTheme: 'emerald',
    buttonText: 'View Results',
  },
];

export const MOCK_QUIZ_QUESTIONS = [
  {
    id: 1,
    question: 'What will be the output of iterating with "range(1, 5)" in Python?',
    options: [
      '1, 2, 3, 4',
      '1, 2, 3, 4, 5',
      '0, 1, 2, 3, 4',
      'Error: StopIteration',
    ],
    correctIndex: 0,
  },
  {
    id: 2,
    question: 'Which statement immediately exits a loop regardless of the test condition?',
    options: ['continue', 'break', 'pass', 'return'],
    correctIndex: 1,
  },
  {
    id: 3,
    question: 'What is the time complexity of searching in a balanced Binary Search Tree?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
    correctIndex: 2,
  },
  {
    id: 4,
    question: 'In JavaScript, which operator checks both value and type equality?',
    options: ['==', '===', '!=', 'equals()'],
    correctIndex: 1,
  },
  {
    id: 5,
    question: 'Which data structure follows the First-In, First-Out (FIFO) principle?',
    options: ['Stack', 'Queue', 'Array', 'Heap'],
    correctIndex: 1,
  },
  {
    id: 6,
    question: 'What keyword defines an anonymous function in Python?',
    options: ['def', 'lambda', 'func', 'anonymous'],
    correctIndex: 1,
  },
  {
    id: 7,
    question: 'Which method adds one or more elements to the end of an array in JavaScript?',
    options: ['push()', 'pop()', 'shift()', 'unshift()'],
    correctIndex: 0,
  },
  {
    id: 8,
    question: 'What is the base case in a recursive function responsible for?',
    options: [
      'Initiating recursion',
      'Preventing infinite loops by terminating',
      'Optimizing memory allocation',
      'Compiling the call stack',
    ],
    correctIndex: 1,
  },
  {
    id: 9,
    question: 'Which traversal visits nodes in: Left, Root, Right order?',
    options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
    correctIndex: 1,
  },
  {
    id: 10,
    question: 'What is the default return value of a function that does not explicitly return in Python?',
    options: ['0', 'False', 'None', 'undefined'],
    correctIndex: 2,
  },
];

export const MOCK_QUIZ_REVIEW_ITEMS = [
  {
    q: '1. What is the time complexity of searching in a balanced BST?',
    userAns: 'O(log n)',
    correctAns: 'O(log n)',
    correct: true,
    points: '1.6 / 1.6',
  },
  {
    q: '2. Which statement immediately exits a loop regardless of the condition?',
    userAns: 'break',
    correctAns: 'break',
    correct: true,
    points: '1.6 / 1.6',
  },
  {
    q: '3. What data structure follows the FIFO principle?',
    userAns: 'Queue',
    correctAns: 'Queue',
    correct: true,
    points: '1.6 / 1.6',
  },
  {
    q: '4. What keyword defines an anonymous function in Python?',
    userAns: 'func',
    correctAns: 'lambda',
    correct: false,
    points: '0.0 / 1.6',
  },
  {
    q: '5. Which traversal visits: Left, Root, Right order?',
    userAns: 'In-order',
    correctAns: 'In-order',
    correct: true,
    points: '1.6 / 1.6',
  },
];
