/**
 * Shared mock data used as fallback when database records are empty or during development.
 */

export const MOCK_STUDENT_COURSES = [
  {
    id: 'mock-1',
    title: 'Intro to Machine Learning',
    courseCode: 'CS401',
    instructorName: 'Dr. Alan Turing',
    progress: 85,
    statusBadge: 'Cors badged',
    bannerUrl: null,
  },
  {
    id: 'mock-2',
    title: 'Linear Algebra II',
    courseCode: 'MATH202',
    instructorName: 'Prof. Katherine Johnson',
    progress: 62,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-3',
    title: 'Advanced Web Development',
    courseCode: 'CS350',
    instructorName: 'Dr. Tim Berners-Lee',
    progress: 78,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-4',
    title: 'Linear Learning',
    courseCode: 'CS410',
    instructorName: 'Dr. Alan Turing',
    progress: 85,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-5',
    title: 'Machine Algebra',
    courseCode: 'MATH305',
    instructorName: 'Prof. Katherine',
    progress: 62,
    statusBadge: 'Status',
    bannerUrl: null,
  },
  {
    id: 'mock-6',
    title: 'Student Development',
    courseCode: 'CS499',
    instructorName: 'Dr. Tim Berners-Lee',
    progress: 78,
    statusBadge: 'Status',
    bannerUrl: null,
  },
];

export const MOCK_CATALOG_COURSES = [
  {
    id: 'cat-1',
    courseCode: 'CS102',
    title: 'Data Structures & Algorithms',
    description: 'Learn fundamental concepts of data structures and machine learning fundamentals.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 98,
  },
  {
    id: 'cat-2',
    courseCode: 'AI201',
    title: 'Deep Learning Foundations',
    description: 'Explore neural networks and advanced AI concepts to build real-world models.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 95,
  },
  {
    id: 'cat-3',
    courseCode: 'DS301',
    title: 'Business Analytics',
    description: 'Explore neural analysis and charts analytics for business contribution.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Waiting List',
    popularity: 88,
  },
  {
    id: 'cat-4',
    courseCode: 'CS102',
    title: 'Data Structures II',
    description: 'Advanced data structure architectures and computational complexity.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 85,
  },
  {
    id: 'cat-5',
    courseCode: 'AI201',
    title: 'Data Learning & Systems',
    description: 'Explore neural networks and advanced AI concepts on modern hardware.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 91,
  },
  {
    id: 'cat-6',
    courseCode: 'DS301',
    title: 'Advanced Analytics',
    description: 'Data pipelines, predictive algorithms, and statistical decision frameworks.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 82,
  },
  {
    id: 'cat-7',
    courseCode: 'CS102',
    title: 'Data Algorithms & Systems',
    description: 'Distributed memory structures, algorithmic optimizers, and cloud caches.',
    semester: 'Fall 2024',
    category: 'Computer Science',
    instructorName: 'Dr. Grace Hopper',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 89,
  },
  {
    id: 'cat-8',
    courseCode: 'AI201',
    title: 'Data Learning & LLMs',
    description: 'Generative transformer models, prompt engineering, and fine-tuning pipelines.',
    semester: 'Fall 2024',
    category: 'Artificial Intelligence',
    instructorName: 'Dr. Andrew Ng',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Waiting List',
    popularity: 96,
  },
  {
    id: 'cat-9',
    courseCode: 'DS301',
    title: 'Quantitative Finance & ML',
    description: 'Algorithmic trading strategies, time-series forecasting, and risk management.',
    semester: 'Fall 2024',
    category: 'Data Science',
    instructorName: 'Dr. John Tukey',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Open',
    popularity: 90,
  },
];
